### ISSUE TITLE
Problem with experiment1.sh

### ISSUE THREAD

**Issue by Lambru99** [danielaLopes/sumo#2]
I follow the commands of the README to install sumo, I resolve the problems related to the missing pip package and I installed numpy 1 instead of the 2 that is not compatible, I already downloaded the dataset from the link provide on the README but when I try to run experiment1.sh it exits with this error:
```
Getting correlated pairs features ...: 1it [00:00, 109.58it/s]
Applying subset sum on possibly correlated pairs ...: 0it [00:00, ?it/s]
Traceback (most recent call last):

  File "/[...]/sumo/sumo_pipeline/session_correlation/app.py", line 280, in <module>
    app()

  File "/[...]/sumo/sumo_pipeline/session_correlation/app.py", line 72, in correlate_sessions
    instance.correlate_sessions(dataset_name, is_full_pipeline=False)

  File "/[...]/sumo/sumo_pipeline/session_correlation/sliding_subset_sum.py", line 405, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^

  File "/[...]/sumo/sumo_pipeline/session_correlation/sliding_subset_sum.py", line 863, in correlate_sessions
    self.__predict(dataset_name)

  File "/[...]/sumo/sumo_pipeline/session_correlation/sliding_subset_sum.py", line 673, in __predict
    self.__run_windowed_subset_sum_on_all_pairs()

  File "/[...]/sumo/sumo_pipeline/session_correlation/sliding_subset_sum.py", line 625, in __run_windowed_subset_sum_on_all_pairs
    scores = sliding_subset_sum.whole_loop_subset_sum(packet_list_clients, packet_list_onions, count_pairs, n_buckets, self.state.delta, self.state.buckets_per_window, self.state.buckets_overlap, n_windows, acc_windows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/[...]/sumo/sumo_pipeline/session_correlation/subsetSumOpenCL2DWrapper.py", line 18, in whole_loop_subset_sum
    acc_windows_array = (ctypes.c_int * nPairs)(*acc_windows)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

IndexError: invalid index
```

**Comment by Daniel1993** [comment]
Can you put a `breakpoint()` in subsetSumOpenCL2DWrapper.py:18? Then print `nPairs` and `acc_windows` and paste it here. By the way, did you compile the C/C++ file? There should be a .so next to the python script (I think the instructions were in the readme).

**Comment by Lambru99** [comment]
> Can you put a breakpoint() in subsetSumOpenCL2DWrapper.py:18? Then print nPairs and acc_windows and paste it here.

```
(sumo) ➜  sumo git:(main) ✗ ./experiment1.sh
make: «torpedosubsetsumopencl2d.so» è aggiornato.
/[...]/.local/share/virtualenvs/sumo--5Hh5JJE/lib/python3.12/site-packages/pytools/persistent_dict.py:63: RecommendedHashNotFoundWarning: Unable to import recommended hash 'siphash24.siphash13', falling back to 'hashlib.sha256'. Run 'python3 -m pip install siphash24' to install the recommended hash.
  warn("Unable to import recommended hash 'siphash24.siphash13', "
/[...]/Documenti/DeanonimaTor/sumo/sumo_pipeline/extract_raw_pcap_features/query_sumo_dataset.py:151: SyntaxWarning: invalid escape sequence '\.'
  sID = re.split('(_request_[0-9]+_client|_request_[0-9]+_hs|_client|_hs)\.pcap$', f_path.split('/')[-1])[0]
/[...]/.local/share/virtualenvs/sumo--5Hh5JJE/lib/python3.12/site-packages/scapy/layers/ipsec.py:512: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  cipher=algorithms.TripleDES,
/[...]/.local/share/virtualenvs/sumo--5Hh5JJE/lib/python3.12/site-packages/scapy/layers/ipsec.py:516: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  cipher=algorithms.TripleDES,
Correlating sessions ...
2024-10-11 10:09:36,021 [INFO] Creating new instance named "results/data/sliding_subset_sum_OSTest.pickle"
2024-10-11 10:09:36,021 [INFO] Instance: Sliding Subset Sum (OSTest)

                    * Baseline (PreProcessedNoFullPipelineState) params => epoch_size: 5;
                    epoch_tolerance: 1;
                    time_sampling_interval: 100;
                    window_size: 4;
                    overlap: 2;
                    delta: 100

                    * Full pipeline (PreProcessedFullPipelineState) params: => epoch_size: 5;
                    epoch_tolerance: 1;
                    time_sampling_interval: 200;
                    window_size: 6;
                    overlap: 3;
                    delta: 60

                    
Getting correlated pairs features ...: 1it [00:00, 110.73it/s]
Applying subset sum on possibly correlated pairs ...: 0it [00:00, ?it/s]
> /[...]/Documenti/DeanonimaTor/sumo/sumo_pipeline/session_correlation/subsetSumOpenCL2DWrapper.py(19)whole_loop_subset_sum()
-> acc_windows_array = (ctypes.c_int * nPairs)(*acc_windows)
(Pdb) p nPairs
0
(Pdb) p acc_windows
[0]
(Pdb) 
```

> By the way, did you compile the C/C++ file? There should be a .so next to the python script (I think the instructions were in the readme).

I run setup.sh but I'm using arch so I installed the packages found here
`sudo apt install python3 ocl-icd-opencl-dev opencl-headers make g++ python3-matplotlib python3-numpy` 
Looking for them on the arch wiki and I proceed to run 
```
echo "Installing python requirements ..."
python3 -m pip install -r requirements.txt

pip3 install -e .
```
All the .so found in the project are:
```
(sumo) ➜  sumo git:(main) ✗ find . -name "*.so"
./sumo_pipeline/session_correlation/torpedosubsetsumopencl2d.so
./sumo_pipeline/session_correlation/subsetsumopencl2d.so
```
Are you looking for them?

**Comment by Daniel1993** [comment]
I think I found the issue, there is a path for the dataset that is hardcoded. Probably the script isn't finding the dataset and stops working (i.e. there are 0 pairs to correlate). I've just pushed commit 61493e6fbcde09362b4cf69739040747aacff3ba with a correction.

**Comment by Lambru99** [comment]
Thanks, it does not stop there anymore but I have another problem in the experiment1, it gives me a segmentation fault:
```

(sumo) ➜  sumo git:(main) ✗ ./experiment1.sh      
make: «torpedosubsetsumopencl2d.so» is updated.
/[...]/Documenti/DeanonimaTor/sumo/sumo_pipeline/extract_raw_pcap_features/query_sumo_dataset.py:151: SyntaxWarning: invalid escape sequence '\.'
  sID = re.split('(_request_[0-9]+_client|_request_[0-9]+_hs|_client|_hs)\.pcap$', f_path.split('/')[-1])[0]
/[...]/.local/share/virtualenvs/sumo--5Hh5JJE/lib/python3.12/site-packages/scapy/layers/ipsec.py:512: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  cipher=algorithms.TripleDES,
/[...]/.local/share/virtualenvs/sumo--5Hh5JJE/lib/python3.12/site-packages/scapy/layers/ipsec.py:516: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  cipher=algorithms.TripleDES,
Correlating sessions ...
2024-10-14 10:10:30,318 [INFO] Creating new instance named "results/data/sliding_subset_sum_OSTest.pickle"
2024-10-14 10:10:30,318 [INFO] Instance: Sliding Subset Sum (OSTest)

                    * Baseline (PreProcessedNoFullPipelineState) params => epoch_size: 5;
                    epoch_tolerance: 1;
                    time_sampling_interval: 100;
                    window_size: 4;
                    overlap: 2;
                    delta: 100

                    * Full pipeline (PreProcessedFullPipelineState) params: => epoch_size: 5;
                    epoch_tolerance: 1;
                    time_sampling_interval: 200;
                    window_size: 6;
                    overlap: 3;
                    delta: 60

                    
Getting correlated pairs features ...:   0%|              | 1/14968 [05:04<1264:14:26, 304.09s/it]
Applying subset sum on possibly correlated pairs ...: 100%|█| 6918/6918 [00:00<00:00, 62616.68it/s
./experiment1.sh: row 5: 177227 segmentation fault (core dump created) python3 app.py correlate-sessions OSTest
```

I think it is correlated with this line:
`os.environ['NUMEXPR_MAX_THREADS'] = str(multiprocessing.cpu_count())` (it is the raw 5 of app.py)

**Comment by Daniel1993** [comment]
I think this:
`./experiment1.sh: row 5: 177227 segmentation fault (core dump created) python3 app.py correlate-sessions OSTest`
refers to ./experiment1.sh line 5, I don't think it breaks on app.py line 5 (which is just reading the number of cores).
I'm not getting this error, so I don't know that is going on.

I found the string "Applying subset sum on possibly correlated pairs" in line 603 of sumo_pipeline/session_correlation/sliding_subset_sum.py, can you try to add breakpoints or prints around that line? I need I bit more information to apply a fix.

**Comment by Lambru99** [comment]
Hi, using the debugger, I found that the error is on this line:
` scores = sliding_subset_sum.whole_loop_subset_sum(packet_list_clients, packet_list_onions, count_pairs, n_buckets, self.state.delta, self.state.buckets_per_window, self.state.buckets_overlap, n_windows, acc_windows)
` (623 more or less)
I tried to print something, but most of the variables are wall of text, so I cannot post them here

**Comment by Daniel1993** [comment]
Probably what is crashing is the `lib.wholeLoopSubsetSum(...)` in subsetSumOpenCL2DWrapper.py, which calls the .so lib that does the correlation.

I bet it is something in the `subsetSum_opencl_2d.cpp`. Try to go into sumo_pipeline/session_correlation, then `make torpedosubsetsumopencl2d_TEST`, then try to run `./torpedosubsetsumopencl2d_TEST` (it may take a while).

Please, check if it runs.

**Comment by Lambru99** [comment]
```
(sumo) ➜  session_correlation git:(main) ✗ make torpedosubsetsumopencl2d_TEST
make: «torpedosubsetsumopencl2d_TEST» is updated.
(sumo) ➜  session_correlation git:(main) ✗ ./torpedosubsetsumopencl2d_TEST
[1]    105845 segmentation fault (core dumped)  ./torpedosubsetsumopencl2d_TEST
```
It seems to be the problem

**Comment by Daniel1993** [comment]
It is a bit weird because it runs on my side. Are you used with gdb? can you compile with debug flags and run the `./torpedosubsetsumopencl2d_TEST` in gdb?

**Comment by hu1ahula** [comment]
In ./experiment1_setup.sh, it `make torpedosubsetsumopencl2d.so`. I guess maybe it didn't make complete then quit for some reasons. However, the `torpedosubsetsumopencl2d.so` still generated but with errors. Maybe you should check weather the OpenCL is correctly installed and write a demo to test it.

**Comment by Daniel1993** [comment]
Thank you for checking this out. Do you have some some information on the errors? Was there any output or was it completely silent?

**Comment by hu1ahula** [comment]
Sorry I didn't save the log info, but there was an Error message about linking the OpenCL library while compiling 'torpedosubsetsumopencl2d.so'. I reconfigured the environment and ran all your experiments successfully.
